# Generated by Django 3.2.4 on 2021-06-15 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco',
            new_name='Enderecos',
        ),
    ]
